UrbanSystemsLab/climateiq-cnn

.github/workflows/python-app.yml, mypy.ini, usl_pipeline/README.md, usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- As each chunk is processed into a feature matrix, update the meta
store for the chunk's study area to maintain the min & max elevation
per study area. We need this information to scale elevation values for
the model.
=> Store Elevation Min & Max Per Study Area

usl_pipeline/usl_lib/tests/readers/test_elevation_readers.py, usl_pipeline/usl_lib/usl_lib/readers/elevation_readers.py
- Previously we expected the nodata_value header to always be present, when the spec states it is optional.
=> Support Optional nodata_value Header

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/study_area_uploader/study_area_uploader/main.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/cloud_storage.py, usl_pipeline/usl_lib/usl_lib/storage/file_names.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Create decorator for cloud function retries & error reporting.
- Create a new cloud function which creates the metastore entry for the study are when files are uploaded to the raw study area file bucket.
- Modify the study area uploader script to stop creating the study area metastore entry and only upload files.
=> Add Cloud Function for Study Area Metastore Creation

terraform/cp_cloud_function_files.sh, terraform/generate_feature_matrix.tf, terraform/main.tf
- Add script cp_cloud_function_files use to prepare the .zip file containing cloud function source code.
- Add terraform config for a cloud function which builds feature tensors for chunks on writes to the chunk bucket.
=> Add Terraform Config for Feature Matrix Creation Cloud Function

terraform/flood_config_functions.tf, usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/readers/test_config_readers.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/readers/config_readers.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Add cloud functions for maintaining state of uploaded CityCAT configs uploaded and removed from GCS.
=> Add Cloud Functions Maintaining CityCAT Metastore Config

terraform/modules/data_pipeline/flood_config_functions.tf, terraform/modules/data_pipeline/generate_feature_matrix.tf, terraform/modules/data_pipeline/main.tf, terraform/modules/data_pipeline/study_area_writes.tf, terraform/modules/data_pipeline/variables.tf
- Introduce a tf region variable and default it to us-central1 for consistency with other buckets.
=> Add Region Var & Use us-central1

terraform/modules/data_pipeline/flood_config_functions.tf, usl_pipeline/usl_lib/usl_lib/storage/cloud_storage.py
climateiq-citycat-config -> climateiq-flood-simulation-config
=> Change CityCAT Config Bucket

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/shared/wps_variables.py
- Create new `wps_variables.py` file to track ordered list of required variables for ML
- Update `build_feature_matrix` to build features matrix with list of required WPS variables stacked
=> [wrf] Modify build_feature_matrix to account for multiple feature vars

usl_pipeline/usl_lib/tests/chunkers/test_raster_chunkers.py, usl_pipeline/usl_lib/usl_lib/chunkers/raster_chunkers.py
- Support breaking a numpy array into sub-array chunks.
=> Add Chunker for Arrays

usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Add helpers for writing & retrieving simulations and simulation label chunks into the metastore.
=> Add Simulation to Metastore

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
- Raise exceptions in the `_retry_and_report_errors decorator` so GCP knows the cloud function failed and can attempt to retry it.
- Add simpler tests for the _retry_and_report_errors decorator.
=> Raise Exceptions to Trigger Retries

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/storage/cloud_storage.py
Process CityCAT Outpus into ML Labels
- Create a cloud function which turns CityCAT rsl output files into
label tensors suitable for machine learning.
=> Process CityCAT Outpus into ML Labels

terraform/modules/data_pipeline/flood_config_functions.tf, terraform/modules/data_pipeline/generate_feature_matrix.tf, terraform/modules/data_pipeline/process_city_cat.tf, terraform/modules/data_pipeline/study_area_writes.tf
- Creates cloud function for code introduce in https://github.com/UrbanSystemsLab/climateiq-cnn/pull/66
=> Add Teraform for CityCAT Label Cloud Function

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
For vars with `z-dimension0012` - each index will correspond to a month (0 for Jan, 11 for Dec). For dimension, we want to extract the value associated with the month of the current WPS output datetime.
=> Apply processing for vars with `z-dimension0012`

usl_pipeline/study_area_uploader/study_area_uploader/transformers/study_area_transformers.py, usl_pipeline/study_area_uploader/tests/transformers/test_study_area_transformers.py, usl_pipeline/usl_lib/tests/readers/test_elevation_readers.py, usl_pipeline/usl_lib/tests/writers/test_elevation_writers.py, usl_pipeline/usl_lib/usl_lib/readers/elevation_readers.py, usl_pipeline/usl_lib/usl_lib/storage/file_names.py, usl_pipeline/usl_lib/usl_lib/writers/elevation_writers.py
This is the first half of the change (on the uploader side). CF part will go as a separate PR.
=> Adding elevation header upload as JSON-file in study_area_uploader

terraform/README.md, terraform/cp_cloud_function_files.sh, terraform/modules/data_pipeline/main.tf
- Move the full creation of the cloud function source .zip file into terraform
=> Remove Need to Run cp_cloud_function_files.sh

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/storage/file_names.py
Create a new cloud function that we'll use to read in uploaded raw WPS files and chunk them into TAR files and upload into `climateiq-study-area-chunks` bucket.
=> [WRF] Create Cloud Function to build and upload study area chunk for wps files

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
Property "chunk_size" is also going to be used in label chunker instead of hardcoded value.
=> [Flood] First part of feature rescaling (storing chunk info in study area metadata)

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Add an 'in_test_set' field to our label chunks.
- Mark each chunk as in the test set or not.
=> Mark Label Chunks Test or Train

usl_models/tests/flood_ml/test_dataset.py, usl_models/usl_models/flood_ml/dataset.py, usl_models/usl_models/flood_ml/model.py
Implement Dataset Generator
builds off of https://github.com/UrbanSystemsLab/climateiq-cnn/pull/112
@Katsutoshii would appreciate some help with some better documentation
=> add dataset generation

usl_models/tests/flood_ml/test_dataset.py, usl_models/usl_models/atmo_ml/model.py, usl_models/usl_models/flood_ml/dataset.py, usl_models/usl_models/flood_ml/model.py
Updates dataset.py to include channels dimension for spatiotemporal tensors and add `load_dataset` implementation.
=> Updates to dataset.py

usl_models/tests/atmo_ml/atmo_model_test.py, usl_models/tests/flood_ml/flood_model_test.py, usl_models/tests/flood_ml/mock_dataset.py, usl_models/usl_models/atmo_ml/model.py, usl_models/usl_models/atmo_ml/model_params.py, usl_models/usl_models/flood_ml/model.py, usl_models/usl_models/flood_ml/model_params.py
- Ensure keras model only takes basic Python types in its constructor to ensure it is serializable.
=> Ensure Model is Serializable

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
Within a study for WRF, we may use subdirectories to further organize output files that come from different sim runs. Currently, if we have an output file in a nested subfolder, a new StudyArea within the metastore would be created named after that subfolder. Instead, we want to ensure that:
1. Root folder determines `StudyArea`
2. StudyAreaChunks are always written in metastore like `<study_area>/chunks/<chunk_name>` regardless of folder organization in source bucket destination
GCS structure
```
/NYC_Heat
/Summer_2010
met_em1.nc
/Summer_2015
met_em20.nc
....
```
should result in
Metastore structure:
```
NYC_Heat            (StudyArea)
/chunks
met_em1      (StudyAreaChunk)
met_em20   (StudyAreaChunk)
...
```
=> [WRF] Ensure nested directories are handled properly in metastore writes

usl_models/usl_models/atmo_ml/model_params.py, usl_models/usl_models/flood_ml/model_params.py
- That's all that will fit in memory!
=> Set the Default Batch Size to 4

usl_pipeline/study_area_uploader/README.md, usl_pipeline/study_area_uploader/study_area_uploader/main.py, usl_pipeline/study_area_uploader/tests/test_main.py
- Add more README information.
- Allow the main.py script to be run directly.
- Change name of argument from 'override' to 'overwrite'
- Remove the chunk size option, as any value besides 1000 will result in issues.
- Provide additional information in the help for arguments.
- Group similar CLI args together.
=> Improve Documentation for Study Area Uploader

usl_models/tests/flood_ml/flood_model_test.py, usl_models/tests/flood_ml/mock_dataset.py, usl_models/usl_models/flood_ml/model.py
Implement batch prediction logic for FloodModel
=> Implement batch prediction logic for FloodModel

usl_models/requirements.txt, usl_models/tests/flood_ml/flood_model_test.py, usl_models/trainer/flood_task.py, usl_models/usl_models/flood_ml/model.py
Support loading a model from an artifact URI.
=> Support loading a model from an artifact URI.

usl_models/tests/flood_ml/flood_eval_test.py, usl_models/usl_models/flood_ml/eval.py
* Updated metrics to compute over individual examples instead of batches
* Batch evaluation is still supported, but batch dimensions are included in the metric computations, which can aggregate away meaningful information
* Added a function for spatial NSE, which is a common time series metric in hydrodynamic modeling
=> Evaluation updates to FloodML

usl_pipeline/usl_lib/usl_lib/shared/wps_data.py
I have added the land use index to the data pipeline. I have added it to the end to the file, as i remember it was required to do so.
I have added it at the end, as it was required by Kathryn, she has already tested the feature/ label matrices.
=> adding land ue index to pipeline

usl_pipeline/usl_lib/usl_lib/shared/wps_data.py
=> solar time added!!!

usl_pipeline/cloud_functions/main.py
Add HTTP triggerable functions for testing data pipeline
=> Add HTTP triggerable functions for testing data pipeline

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
I have added the solar time and tested it in my local.  I have changed the expected values to remove the errors. Could you confirm ? @MadhaviJain90
=> added the solar time

.github/workflows/python-app.yml, usl_pipeline/cloud_functions/main_test.py
Use ubuntu-22.04 instead of ubuntu-latest in GitHub workflows
=> Use ubuntu-22.04 instead of ubuntu-latest in GitHub workflows

.github/workflows/python-app.yml
=> Rename Cloud Functions CI

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/notebooks/test_cloud_functions.ipynb
Fix build_wrf_label_matrix_http to return a dict instead of a set
=> Fix build_wrf_label_matrix_http to return a dict instead of a set

usl_models/notebooks/train_atmo_model.ipynb, usl_models/tests/atmo_ml/atmo_model_test.py, usl_models/tests/atmo_ml/dataset_test.py, usl_models/usl_models/atmo_ml/constants.py, usl_models/usl_models/atmo_ml/dataset.py, usl_models/usl_models/atmo_ml/model.py, usl_models/usl_models/atmo_ml/vars.py, usl_models/usl_models/atmo_ml/visualizer.py, usl_models/usl_models/shared/downloader.py
Add support for selecting custom number of timesteps in dataset.
=> Add support for selecting custom number of timesteps in dataset.

usl_models/tests/atmo_ml/atmo_model_test.py, usl_models/usl_models/atmo_ml/metrics.py, usl_models/usl_models/atmo_ml/model.py, usl_models/usl_models/atmo_ml/vars.py
Add metrics and update model checkpoint test.
=> Add metrics and update model checkpoint test.

usl_models/pytest.ini, usl_pipeline/study_area_uploader/pytest.ini, usl_pipeline/usl_lib/pytest.ini
=> Add pytest.ini files.

usl_models/notebooks/train_atmo_model.ipynb, usl_models/tests/atmo_ml/atmo_model_test.py, usl_models/tests/atmo_ml/dataset_test.py, usl_models/usl_models/atmo_ml/constants.py, usl_models/usl_models/atmo_ml/dataset.py, usl_models/usl_models/atmo_ml/model.py, usl_models/usl_models/shared/keras_dataclasses.py
Migrate AtmoModel.Params to a dataclass, which is easier to have defaults with.
=> AtmoModel.Params dataclass

usl_models/notebooks/htune_atmo_model.ipynb, usl_models/notebooks/train_atmo_model.ipynb, usl_models/requirements.txt, usl_models/setup.py, usl_models/usl_models/atmo_ml/model.py
Support hyperparameter tuning.
=> Support hyperparameter tuning.

usl_models/tests/atmo_ml/atmo_model_test.py, usl_models/usl_models/atmo_ml/model.py
Use loaded model parameters in from_checkpoint.
=> Use loaded model parameters in from_checkpoint.

usl_models/tests/atmo_ml/atmo_model_test.py, usl_models/tests/flood_ml/flood_model_test.py, usl_models/usl_models/flood_ml/model.py, usl_models/usl_models/flood_ml/model_params.py
Replace tf.keras with keras so we will always use the same backend.
=> Replace tf.keras with keras

usl_pipeline/usl_lib/tests/transformers/hecras_output_transformers.py, usl_pipeline/usl_lib/usl_lib/transformers/hecras_output_transformers.py
Utility to read and extract depth information from HECRAS output to RSL file format.
=> Add library to read and transform hecras output to RSL file format.
