UrbanSystemsLab/climateiq-cnn

.flake8
- adopt the minimal configuration to make flake8 compatible with black https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#minimal-configuration
=> flake8 black compat

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/storage/cloud_storage.py
- Log exceptions to get better error messages in the CloudFunction UI for errors.
- Implment retry logic allowing cloud functions to retry until for a set period of time after they are first tried.
- Write errors encountered during chunk processing to the metastore entry for that chunk.
- Correct cloud bucket name climateiq-study_area -> climateiq-study-area
- Pass Python rather than Numpy floats into firestore client methods.
=> Improve Error Handling & Implement Retries

usl_models/tests/model_test.py, usl_models/usl_models/flood_ml/model.py, usl_models/usl_models/flood_ml/model_params.py
Set up some initial components for the model pipeline, including a very naive training step.
- The newly-created `FloodModel` class will be how the user interfaces with the model for training, evaluation, and prediction, rather than using the Keras-based `FloodConvLSTM`.
- The `FloodModelParams` dataclass is a structured way to pass in configurable model parameters with better type checking and well-defined parameter names and default values.
Functional changes:
- We're no longer caching the `geo_cnn` output. This would have prevented the model from backpropagating correctly and updating the weights. We can consider introducing a caching mechanism for prediction at a later time.
=> Create FloodModel and FloodModelParams for model API

terraform/flood_config_functions.tf, usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/readers/test_config_readers.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/readers/config_readers.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Write the CityCAT rainfall configuration files as a numpy array into GCS as the config files are uploaded.
=> Create Rainfall Config Features

terraform/flood_config_functions.tf, usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/readers/test_config_readers.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/readers/config_readers.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Only attempt to write feature chunk errors to the metastore from the feature chunk cloud function. Accomplish this by adding an argument to the `retry_and_report_errors` decorator for additional custom error handling and adding the additional metastore write when decorating the feature chunk cloud function.
=> Only Write Chunk Errors From Chunk Cloud Function

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Record the un-padded number of timesteps in the rainfall vector. Model training needs access to this so it knows how many timesteps to train against in the auto-regressive loop.
=> Write Un-Padded Number of Rainfall Entries to Metastore

usl_models/tests/model_test.py, usl_models/usl_models/flood_ml/constants.py, usl_models/usl_models/flood_ml/data_utils.py, usl_models/usl_models/flood_ml/model.py
The model will now accept a list of inputs, grouped by storm duration, and will fit on them incrementally.
Data are now expected to be structured as FloodModelData objects, which provides better validation.
=> Allow FloodModel to accept multiple storm durations

usl_pipeline/study_area_uploader/study_area_uploader/transformers/elevation_transformers.py, usl_pipeline/usl_lib/tests/readers/test_simulation_readers.py, usl_pipeline/usl_lib/usl_lib/readers/simulation_readers.py, usl_pipeline/usl_lib/usl_lib/shared/geo_data.py
- Add a reader for CityCAT rsl output files which returns their flood predictions as a raster.
- Factor out forward_transform & back_transform methods for building affines from elevation headers.
=> Add Reader for CityCAT Simulation Files

terraform/flood_config_functions.tf, terraform/generate_feature_matrix.tf, terraform/study_area_writes.tf
- Create terraform configuration for a cloud function which responds to writes to a study area bucket.
- Rename google_service_account.account to google_service_account.generate_feature_matrix as we define several service accounts.
=> Create Terraform Configuration for Study Area Write CF

usl_pipeline/study_area_uploader/study_area_uploader/main.py, usl_pipeline/study_area_uploader/study_area_uploader/transformers/soil_classes_transformers.py, usl_pipeline/study_area_uploader/study_area_uploader/transformers/study_area_transformers.py, usl_pipeline/study_area_uploader/tests/transformers/test_soil_classes_transformers.py, usl_pipeline/study_area_uploader/tests/transformers/test_study_area_transformers.py, usl_pipeline/usl_lib/usl_lib/transformers/polygon_transformers.py, usl_pipeline/usl_lib/usl_lib/transformers/raster_transformers.py
This is a modification of the algorithm that reconstructs (or classify) green areas based on soil classes. It takes into account the requirement to exclude non-green area soil classes.
Before this change algorithm had the following steps:
1) Exclude from soil class polygons all parts of regions that are outside green areas, and report them to CityCat;
2) Classify soil classes for all raster cells from green areas that weren't covered by any soil classes using nearest neighbor approach looking for nearest soil class polygons, and report them as 1-cell polygons to CityCat in addition to item 1.
After the change:
1) Exclude from soil class polygons all parts of regions that are outside green areas, *also filter out polygons with non-green soil classes*, and report them as polygons to …
=> Exclusion logic for special soil classes that cannot be marked as green areas

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/cloud_functions/requirements.txt
Add initial logic and unit test for modifying `build_feature_matrix` to handle wps files for AtmoML. Follow-up PRs will address:
- setting up the appropriate matrix transforms on the WPS variables that are in-scope for ML training
- writing to metastore
=> Extend build_feature_matrix_from_archive to handle heat modeling files

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
- Use 'uri' rather than 'path' for fields containing the full GCS URI
- Allow creating, deleting and retrieving `FloodScenarioConfig`s by ID rather than full URI.
- Add `get_ref` method for FloodScenarioConfig and StudyArea and refactor to use it internally.
- Add `as_header` method to StudyArea objects.
=> Some Metastore Refactoring

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
Variables in WRF/WPS will always be associated with some list of dimensions. The list of dimensions associated with each variable may vary depending on the nature of the variable. Typically, the dimensions could be `Time`, `south_north` (lon), `west_east` (lat), `some-z-dim`, `some-z-dim-1`, etc
Ordering of the dimensions follow a general convention of `Time`, `z`, `lon`, `lat` but may not always be consistent and the z dimension may also vary - see more: https://www.bic.mni.mcgill.ca/users/sean/Docs/netcdf/guide.txn_22.html.
We'll add an initial transform to set the axis order to always be `west_east` (lon), `south_north` (lat), `<other_spatial_dims>` to ensure consistency when processing the feature matrix (especially when extracting values from certain z dimensions, ex: …
=> [WRF] Fix the order of netcdf spatial dimensions to always be: (lon, lat, ...)

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/shared/wps_data.py
Prior to performing feature engineering work on each feature DataArray, we'll first derive any custom, non-native WPS variables of interest.
For this initial case, we will compute 10m Wind Speed (`WSPD10`) and Wind Direction (`WDIR10`) from existing, standard variables `UU` and `VV` (wind vectors).
=> [WRF] Derive custom WPS variables: WSPD10, WDIR10

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
Since we are treating one WPS file as one study area chunk, there is no need at this point to package this file into an archive for processing. Instead, we will load one WPS file (un-tarred) as a chunk and trigger `build_feature_matrix()` to process the netcdf file.
=> [WRF] Refactor build_feature_matrix to process un-tarred WRF input files

usl_models/tests/model_test.py, usl_models/usl_models/flood_ml/model.py, usl_models/usl_models/flood_ml/model_params.py
Added optional early stopping to the FloodML model.
Also fixed a bug in the FloodModelParams dataclass. The default optimizer is being used across all instances of the dataclass that don't specify a different value. Because this is currently a keras.Optimizer object, that same object is getting passed to possibly multiple models, which will throw an error. Changed this to a string, which is also a valid optimizer value. As with all other model parameters, we leave it to the user to supply reasonable values.
=> Add early stopping support to FloodML

usl_pipeline/cloud_functions/main.py
- To ensure idempotency, ignore deletes of already-deleted objects.
=> Ignore Not-Found Exceptions When Deleting GCS Objects

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/cloud_functions/requirements.txt
When raw WPS files are first uploaded into `climateiq-atmospheric-simulation-input` GCS bucket, in-scope WPS file will be uploaded as a study area chunk. When this occurs, we will additionally write to metastore to create a new entry for this study area.
CRS value will be derived from a cartopy projection that utilize's wps file's map_projection value (lambert, meridian, etc). We will use the source_crs to populate the metastore entry
=> [WRF] Create new study area metastore entry when raw WPS file is uploaded

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
* Update parsing for timestamp from netfdf when writing to metastore - needs to be decoded (similar to what is done for labels: https://github.com/UrbanSystemsLab/climateiq-cnn/pull/97)
* Fix chunk_path reference so it is accessible by wrf's sectino of the if/else statement
=> [WRF] Bug fixes for build_feature_matrix for wps

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
The root cause we're trying to solve in this PR is the following. Before this PR we had a logic avoiding retry for build_feature_matrix CF if the chunk metadata is already present. But if the error happens in this CF we do create chunk metadata object with just error field populated which now blocks retry (it does detect the presence of chunk metadata and stops but it shouldn't in case of previous error).
=> Fix for study area chunk metadata initialized too early due to error/retry

usl_pipeline/cloud_functions/main.py
- Change variable names min & max -> scaling_min & scaling max to avoid shadowing the builtin min & max functions.
=> Avoid Shadowing Builtins min & max

usl_models/tests/flood_ml/flood_model_test.py, usl_models/usl_models/flood_ml/model_params.py
Removed the `test_model_params` instance and created a helper function for testing, which will create and return an object as needed.
This also removes the previous behavior where every test was using the same instance, which could cause unintended side effects (such as changing member values).
=> Clean up test_model_params.

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
After this change any flood study area metadata will be in 1 of 4 states:
- INIT (set when study area metadata is created for first time as a result of `header.json` file processing in CF).
- CHUNKS_UPLOADED (when all the chunk TAR-files are stored to the bucket and all the feature building CF triggers are started but not finished yet; though we need at least one of the chunks being fully processed to get chunk-related properties in study area metadata in order to be able to calculate the expected number of chunks overall)
- FEATURE_MATRICES_CREATED (all the feature building CFs are executed and unscaled feature matrix files are stored)
- RESCALING_DONE (all the feature matrix files are scaled).
=> Support for updates of study area state during the feature chunk processing

usl_models/requirements.txt
- This package fails to install in Windows, as there are no wheels supplied for it.
=> Skip tensorflow-io-gcs-filesystem Package for Windows

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
1. Bug: Firestore document id restrict use of certain chars
* Fix: Sanitize doc ids - replace all "." and ":" from chunk name with underscore before using it as document id
2. Bug: In `build_and_upload_study_area_chunk()`, nc file could not be opened from python stream due to invalid arg
* Fix: Since stream was first used in GCS upload before being read again to create in memory dataset, it needs to be seeked to beginning
3. Bug: metastore.StudyArea failed to persist x_ll_corner and y_ll_corner due to invalid type
* Fix: Convert values from numpy.float32 -> float
=> [WRF] Fix metastore bugs from feature matrix pipeline

usl_pipeline/cloud_functions/requirements.txt
Fixes bug when CF attempts to write to metastore and utilizes cartopy to extract CRS value
=> [WRF] Add missing `cartopy` package in requirements.txt

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/tests/integration/test_metastore_integration.py, usl_pipeline/usl_lib/tests/storage/test_metastore.py, usl_pipeline/usl_lib/usl_lib/storage/metastore.py
Add a validation set. This is now a 60/20/20 train/val/test split, indicated by the `dataset` flag in the metastore.
=> Add a validation split to label chunks

usl_models/tests/flood_ml/flood_model_test.py, usl_models/tests/flood_ml/test_dataset.py, usl_models/tests/integration/test_metastore_integration.py, usl_models/trainer/flood_task.py, usl_models/usl_models/flood_ml/dataset.py, usl_models/usl_models/flood_ml/metastore.py, usl_models/usl_models/flood_ml/model.py
Updated `load_dataset` to retrieve a specific dataset split: either train, val, or test. The training script now includes a validation set.
=> Retrieve separate train/val/test datasets

usl_models/tests/integration/test_metastore_integration.py, usl_models/usl_models/flood_ml/metastore.py
We were filtering on the wrong field name, which was causing model training to fail on empty inputs.
=> Fix incorrect field name in model dataset

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/storage/file_names.py
- The rescaling logic is only implemented for flood. Skip WRF files triggering the function.
- Log file names we see from the cloud function decorator.
=> Avoid Scaling Files From WRF Pipeline

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py, usl_pipeline/usl_lib/usl_lib/shared/wps_data.py
Update our wind direction computation to split out sin and cos components - code extracted from source: https://github.com/UrbanSystemsLab/climateiq-cnn/pull/114
=> [WRF] Update wind derivation to split out cos/sin components

usl_models/tests/flood_ml/test_dataset.py, usl_models/tests/integration/test_metastore_integration.py, usl_models/usl_models/flood_ml/dataset.py, usl_models/usl_models/flood_ml/metastore.py, usl_models/usl_models/flood_ml/prediction_dataset.py
Folks,
Please review these changes to support prediction dataset.  You should see output like this:
```study_area = "NYC"
city_cat_config = "config_v1%2FRainfall_Data_1.txt"
dataset = load_prediction_dataset(study_area=study_area, city_cat_config=city_cat_config, batch_size=1, max_chunks=1)
input_tuple = next(iter(dataset))
model_input, metadata = input_tuple
print("Model Input:")
for key, value in model_input.items():
print(f"Key: {key}")
print(f"Shape: {value.shape}")
print("-" * 20)
print("Metadata:")
for key, value in metadata.items():
if key == 'feature_chunk':
decoded_value = value.numpy()[0].decode('utf-8')
print(f"Key: {key}")
print(f"Value: {decoded_value}")
else:
print(f"Key: {key}")
print(f"Value: {value.numpy()}")  # Convert tensor to numpy for display
print("-" * 20)```
=> changes to support prediction dataset

usl_pipeline/usl_lib/usl_lib/storage/file_names.py
Filenames may sometimes use `_` and other times `.` - example:
met_em.d03.2010-05-22_00:00:00.nc
wrfout_d03_2015-06-25_15:00:00
Relax regex for both cases to handle both.
=> [WRF] Relax regex for WPS and WRF filenames

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
Splitting wind direction to sin and cos in labels
=> Splitting wind direction to sin and cos in labels

.github/workflows/python-app.yml, usl_models/tests/atmo_ml/datasets_test.py, usl_models/tests/atmo_ml/test_cnn_inputs_outputs.py, usl_models/usl_models/atmo_ml/cnn_inputs_outputs.py, usl_models/usl_models/atmo_ml/datasets.py
I have added firestore for logging & Prediction to the datasets.py file along with testing files.
=> firestore & Prediction

.github/workflows/python-app.yml
We shouldn't do merge before updating the branch protection rule to fix the typo
=> Revert "Rename Cloud Functions CI"

usl_pipeline/cloud_functions/main.py, usl_pipeline/cloud_functions/main_test.py
Current we are writing atmo ML features as <timestamp>/<vartype>.npy files. This change updates that to <vartype>/<timestamp>.npy to make loading tensors easier in dataset.py.
=> Swap vartype directory structure

usl_models/notebooks/train_atmo_model.ipynb, usl_models/usl_models/atmo_ml/model.py
Separate model param input_cnn_kernel_size.
=> Separate model param input_cnn_kernel_size.
